version: '3.8'

services:
  # Database Service
  database:
    image: mysql:8.0
    container_name: apartments_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: apartments_db
      MYSQL_USER: apartments_user
      MYSQL_PASSWORD: apartments_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - apartments_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: apartments_backend
    restart: always
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USERNAME=apartments_user
      - DB_PASSWORD=apartments_password
      - DB_DATABASE=apartments_db
    depends_on:
      database:
        condition: service_healthy
    networks:
      - apartments_network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: apartments_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - apartments_network

volumes:
  mysql_data:

networks:
  apartments_network:
    driver: bridge